import { Download, FileSpreadsheet, FileText, Sparkles } from "lucide-react";
import { getTranslations } from "next-intl/server";
import { DashboardTopbar } from "@/components/dashboard/topbar";
import { AttendanceTrendChart } from "@/components/dashboard/attendance-trend-chart";
import { OvertimeBarChart } from "@/components/dashboard/overtime-bar-chart";
import { KpiLineChart } from "@/components/dashboard/kpi-line-chart";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { getAttendanceTrend } from "@/lib/data";

export default async function ReportsPage() {
  const [t, trend] = await Promise.all([
    getTranslations("dashboard.reports"),
    getAttendanceTrend(14),
  ]);

  const otByDept = [
    { dept: "Production", hours: 142 },
    { dept: "Maintenance", hours: 38 },
    { dept: "Warehouse", hours: 24 },
    { dept: "HR", hours: 6 },
    { dept: "Mgmt", hours: 0 },
  ];

  const kpiTrend = [
    { month: "Nov", score: 84 },
    { month: "Dec", score: 86 },
    { month: "Jan", score: 88 },
    { month: "Feb", score: 87 },
    { month: "Mar", score: 90 },
    { month: "Apr", score: 92 },
    { month: "May", score: 93 },
  ];

  return (
    <>
      <DashboardTopbar title={t("title")} subtitle={t("subtitle")} />
      <main className="flex-1 px-6 py-6">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex items-center gap-2">
            <Badge variant="muted">Last 14 days</Badge>
            <Badge variant="muted">All departments</Badge>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm">
              <Sparkles className="h-3.5 w-3.5" />
              AI summary
            </Button>
            <Button variant="outline" size="sm">
              <FileSpreadsheet className="h-3.5 w-3.5" />
              {t("exportExcel")}
            </Button>
            <Button size="sm">
              <FileText className="h-3.5 w-3.5" />
              {t("exportPdf")}
            </Button>
          </div>
        </div>

        <div className="mt-6 grid gap-4 lg:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>{t("punctuality")}</CardTitle>
              <CardDescription>On-time vs late check-ins (14 days)</CardDescription>
            </CardHeader>
            <CardContent>
              <AttendanceTrendChart data={trend} />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>{t("overtimeTrend")}</CardTitle>
              <CardDescription>Overtime hours by department · this month</CardDescription>
            </CardHeader>
            <CardContent>
              <OvertimeBarChart data={otByDept} />
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>{t("kpiTrend")}</CardTitle>
              <CardDescription>Average performance score · 7 months</CardDescription>
            </CardHeader>
            <CardContent>
              <KpiLineChart data={kpiTrend} />
            </CardContent>
          </Card>

          <Card className="border-orange-200 bg-orange-50/30">
            <CardHeader>
              <div className="flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-orange-500" />
                <CardTitle className="text-orange-700">AI summary</CardTitle>
              </div>
              <CardDescription>Generated by EC AIHR Assistant from raw report data</CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-sm text-navy-700">
              <p>
                <span className="font-semibold">Headline:</span> attendance is steady at 92%, with
                lateness down 17% over the last 14 days — driven by Production line A.
              </p>
              <p>
                <span className="font-semibold">Watchpoint:</span> overtime in Production has
                outpaced budget by 14h. Recommend reviewing rotation patterns for Group B.
              </p>
              <p>
                <span className="font-semibold">KPI:</span> 7-month upward trend (84 → 93). EMP002
                and EMP006 are the top two contributors.
              </p>
              <Button variant="outline" size="sm" className="border-orange-300 text-orange-700 hover:bg-orange-100">
                <Download className="h-3.5 w-3.5" />
                Download as PDF
              </Button>
            </CardContent>
          </Card>
        </div>
      </main>
    </>
  );
}
